export const TASKS_ITEMS = [
  {
    imageUrl: require('../assets/tasks/textSummary.png'),
    name: 'TEXT_SUMMARY',
    desc: 'DESC_TEXT_SUMMARY',
    firstMessage: 'FIRST_MESSAGE_TEXT_SUMMARY',
    isPopular: true,
    category: 'EDUCATION',
    query: 'QUERY_TEXT_SUMMARY',
  },
  {
    imageUrl: require('../assets/tasks/writing.png'),
    name: 'WRITING',
    desc: 'DESC_WRITING',
    firstMessage: 'FIRST_MESSAGE_WRITING',
    isPopular: true,
    category: 'EDUCATION',
    query: 'QUERY_WRITING',
  },
  {
    imageUrl: require('../assets/tasks/rewriting.png'),
    name: 'REWRITING',
    desc: 'DESC_REWRITING',
    firstMessage: 'FIRST_MESSAGE_REWRITING',
    isPopular: true,
    category: 'EDUCATION',
    query: 'QUERY_REWRITING',
  },
  {
    imageUrl: require('../assets/tasks/textCheck.png'),
    name: 'TEXT_CHECK',
    desc: 'DESC_TEXT_CHECK',
    firstMessage: 'FIRST_MESSAGE_TEXT_CHECK',
    isPopular: true,
    category: 'EDUCATION',
    query: 'QUERY_TEXT_CHECK',
  },
  {
    imageUrl: require('../assets/tasks/insta.png'),
    name: 'CONTENT',
    desc: 'DESC_CONTENT',
    firstMessage: 'FIRST_MESSAGE_CONTENT',
    isPopular: true,
    category: 'SOCIAL_MEDIA',
    query: 'QUERY_CONTENT',
  },
  {
    imageUrl: require('../assets/tasks/insta.png'),
    name: 'CAPTIONS',
    desc: 'DESC_CAPTIONS',
    firstMessage: 'FIRST_MESSAGE_CAPTIONS',
    isPopular: true,
    category: 'SOCIAL_MEDIA',
    query: 'QUERY_CAPTIONS',
  },
  {
    imageUrl: require('../assets/tasks/facebook.png'),
    name: 'FACEBOOK',
    desc: 'DESC_FACEBOOK',
    firstMessage: 'FIRST_MESSAGE_FACEBOOK',
    isPopular: true,
    category: 'SOCIAL_MEDIA',
    query: 'QUERY_FACEBOOK',
  },
  {
    imageUrl: require('../assets/tasks/essay.png'),
    name: 'ESSAY',
    desc: 'DESC_ESSAY',
    firstMessage: 'FIRST_MESSAGE_ESSAY',
    isPopular: true,
    category: 'EDUCATION',
    query: 'QUERY_ESSAY',
  },
  {
    imageUrl: require('../assets/tasks/insta.png'),
    name: 'REELS',
    desc: 'DESC_REELS',
    firstMessage: 'FIRST_MESSAGE_REELS',
    isPopular: true,
    category: 'SOCIAL_MEDIA',
    query: 'QUERY_REELS',
  },
  {
    imageUrl: require('../assets/tasks/tiktok.png'),
    name: 'TIKTOK',
    desc: 'DESC_TIKTOK',
    firstMessage: 'FIRST_MESSAGE_TIKTOK',
    isPopular: true,
    category: 'SOCIAL_MEDIA',
    query: 'QUERY_TIKTOK',
  },
  {
    imageUrl: require('../assets/tasks/aiArt.png'),
    name: 'AI_ART',
    desc: 'DESC_AI_ART',
    firstMessage: 'FIRST_MESSAGE_AI_ART',
    isPopular: true,
    category: 'FUN',
    query: 'QUERY_AI_ART',
  },
  {
    imageUrl: require('../assets/tasks/reply.png'),
    name: 'REPLY_IDEAS',
    desc: 'DESC_REPLY_IDEAS',
    firstMessage: 'FIRST_MESSAGE_REPLY_IDEAS',
    isPopular: true,
    category: 'COMMUNICATION',
    query: 'QUERY_REPLY_IDEAS',
  },
  {
    imageUrl: require('../assets/tasks/textStyle.png'),
    name: 'TEXT_STYLE',
    desc: 'DESC_TEXT_STYLE',
    firstMessage: 'FIRST_MESSAGE_TEXT_STYLE',
    isPopular: true,
    category: 'EDUCATION',
    query: 'QUERY_TEXT_STYLE',
  },
  {
    imageUrl: require('../assets/tasks/tiktok.png'),
    name: 'TIKTOK',
    desc: 'DESC_TIKTOK',
    firstMessage: 'FIRST_MESSAGE_TIKTOK',
    category: 'SOCIAL_MEDIA',
    query: 'QUERY_TIKTOK',
  },
  {
    imageUrl: require('../assets/tasks/linkedn.png'),
    name: 'LINKEDIN_PROFILE',
    desc: 'DESC_LINKEDIN_PROFILE',
    firstMessage: 'FIRST_MESSAGE_LINKEDIN_PROFILE',
    category: 'SOCIAL_MEDIA',
    query: 'QUERY_LINKEDIN_PROFILE',
  },
  {
    imageText: '🔖',
    name: 'CHATTING',
    desc: 'DESC_CHATTING',
    firstMessage: 'FIRST_MESSAGE_CHATTING',
    category: 'SOCIAL_MEDIA',
    query: 'QUERY_CHATTING',
  },
  {
    imageUrl: require('../assets/tasks/x.png'),
    name: 'X_PROFILE',
    desc: 'DESC_X_PROFILE',
    firstMessage: 'FIRST_MESSAGE_X_PROFILE',
    category: 'SOCIAL_MEDIA',
    query: 'QUERY_X_PROFILE',
  },
  {
    imageUrl: require('../assets/tasks/x.png'),
    name: 'X_POSTS',
    desc: 'DESC_X_POSTS',
    firstMessage: 'FIRST_MESSAGE_X_POSTS',
    category: 'SOCIAL_MEDIA',
    query: 'QUERY_X_POSTS',
  },
  {
    imageText: '🦹‍♀️',
    name: 'ROLEPLAY',
    desc: 'DESC_ROLEPLAY',
    firstMessage: 'FIRST_MESSAGE_ROLEPLAY',
    category: 'SOCIAL_MEDIA',
    query: 'QUERY_ROLEPLAY',
  },
  {
    imageText: '😔',
    name: 'THERAPIST',
    desc: 'DESC_THERAPIST',
    firstMessage: 'FIRST_MESSAGE_THERAPIST',
    category: 'COMMUNICATION',
    query: 'QUERY_THERAPIST',
  },
  {
    imageText: '💘',
    name: 'FLIRTING',
    desc: 'DESC_FLIRTING',
    firstMessage: 'FIRST_MESSAGE_FLIRTING',
    category: 'COMMUNICATION',
    query: 'QUERY_FLIRTING',
  },
  {
    imageText: '💘',
    name: 'ROMANCE',
    desc: 'DESC_ROMANCE',
    firstMessage: 'FIRST_MESSAGE_ROMANCE',
    category: 'COMMUNICATION',
    query: 'QUERY_ROMANCE',
  },
  {
    imageText: '🤖',
    name: 'UNDETECTABLE_AI',
    desc: 'DESC_UNDETECTABLE_AI',
    firstMessage: 'FIRST_MESSAGE_UNDETECTABLE_AI',
    category: 'EDUCATION',
    query: 'QUERY_UNDETECTABLE_AI',
  },
  {
    imageText: '📏',
    name: 'MATH',
    desc: 'DESC_MATH',
    firstMessage: 'FIRST_MESSAGE_MATH',
    category: 'EDUCATION',
    query: 'QUERY_MATH',
  },
  {
    name: 'CODING_QUESTIONS',
    imageText: '💻',
    desc: 'DESC_CODING_QUESTIONS',
    firstMessage: 'FIRST_MESSAGE_CODING_QUESTIONS',
    category: 'EDUCATION',
    query: 'QUERY_CODING_QUESTIONS',
  },
  {
    name: 'PHYSIC_QUESTIONS',
    imageText: '👩‍🔬',
    desc: 'DESC_PHYSIC_QUESTIONS',
    firstMessage: 'FIRST_MESSAGE_PHYSIC_QUESTIONS',
    category: 'EDUCATION',
    query: 'QUERY_PHYSIC_QUESTIONS',
  },
  {
    name: 'LYRICS',
    imageText: '🎵',
    desc: 'DESC_LYRICS',
    firstMessage: 'FIRST_MESSAGE_LYRICS',
    category: 'FUN',
    query: 'QUERY_LYRICS',
  },
  {
    name: 'POEM',
    imageText: '📜',
    desc: 'DESC_POEM',
    firstMessage: 'FIRST_MESSAGE_POEM',
    category: 'FUN',
    query: 'QUERY_POEM',
  },
  {
    name: 'STORY',
    imageText: '📖',
    desc: 'DESC_STORY',
    firstMessage: 'FIRST_MESSAGE_STORY',
    category: 'FUN',
    query: 'QUERY_STORY',
  },
  {
    name: 'SHORT_FILM',
    imageText: '🎬',
    desc: 'DESC_SHORT_FILM',
    firstMessage: 'FIRST_MESSAGE_SHORT_FILM',
    category: 'FUN',
    query: 'QUERY_SHORT_FILM',
  },
  {
    name: 'COMPANY_BIO',
    imageText: '📋',
    desc: 'DESC_COMPANY_BIO',
    firstMessage: 'FIRST_MESSAGE_COMPANY_BIO',
    category: 'BUSINESS',
    query: 'QUERY_COMPANY_BIO',
  },
  {
    name: 'NAME_GENERATOR',
    imageText: '🔖',
    desc: 'DESC_NAME_GENERATOR',
    firstMessage: 'FIRST_MESSAGE_NAME_GENERATOR',
    category: 'BUSINESS',
    query: 'QUERY_NAME_GENERATOR',
  },
  {
    name: 'SLOGAN',
    imageText: '📢',
    desc: 'DESC_SLOGAN',
    firstMessage: 'FIRST_MESSAGE_SLOGAN',
    category: 'BUSINESS',
    query: 'QUERY_SLOGAN',
  },
  {
    name: 'ADS',
    imageText: '💫',
    desc: 'DESC_ADS',
    firstMessage: 'FIRST_MESSAGE_ADS',
    category: 'BUSINESS',
    query: 'QUERY_ADS',
  },
  {
    name: 'JOB_ADS',
    imageText: '📰',
    desc: 'DESC_JOB_ADS',
    firstMessage: 'FIRST_MESSAGE_JOB_ADS',
    category: 'BUSINESS',
    query: 'QUERY_JOB_ADS',
  },
];
